"""Exotic priority functions."""
import sys, os, math
import numpy as np
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from importlib import import_module
m = import_module("000-batch-tester")
bench = m.bench

n = 8

# c2=3 cluster broken with subtle inner orderings
def make_c2_3_inner(secondary):
    def p(e, n):
        c2 = sum(1 for x in e if x == 2)
        return -1e6 * abs(c2 - 3) + secondary(e, n)
    return p

# Sort within c2=3 by (sum of 2-positions, then lex-of-fill)
def s_pos2_then_fill(e, n):
    pos = sum(i for i, x in enumerate(e) if x == 2)
    fill = sum(b * 2**i for i, b in enumerate(x for x in e if x != 2))
    return -pos * 32 - fill

def s_fill_lex(e, n):
    fill_idx = 0
    for x in e:
        if x != 2:
            fill_idx = fill_idx * 2 + x
    return -float(fill_idx)

def s_pattern_lex(e, n):
    pat = tuple(i for i, x in enumerate(e) if x == 2)
    if len(pat) == 3:
        idx = pat[0] * 64 + pat[1] * 8 + pat[2]
    else:
        idx = 0
    return -float(idx)

def s_pattern_lex_rev(e, n):
    pat = tuple(i for i, x in enumerate(e) if x == 2)
    if len(pat) == 3:
        idx = pat[0] * 64 + pat[1] * 8 + pat[2]
    else:
        idx = 0
    return float(idx)

bench("c2=3 with custom secondary 1", make_c2_3_inner(s_pos2_then_fill), n)
bench("c2=3 with fill-lex secondary", make_c2_3_inner(s_fill_lex), n)
bench("c2=3 with pattern-lex sec", make_c2_3_inner(s_pattern_lex), n)
bench("c2=3 with pattern-lex-rev sec", make_c2_3_inner(s_pattern_lex_rev), n)

# Try huge variety of priority functions inspired by combinations
print("\n--- composite features ---")

def p_sum_of_e(e, n):
    return -float(sum(e) % 3)

def p_neg_sum(e, n):
    return float(sum(e) % 3)

def p_squared_l2(e, n):
    return float(sum(x*x for x in e))

def p_l1(e, n):
    return -float(sum(e))

def p_count_pairs_match(e, n):
    return -float(sum(1 for i in range(n-1) if e[i] == e[i+1]))

def p_count_consec_diff(e, n):
    return float(sum(1 for i in range(n-1) if e[i] != e[i+1]))

bench("sum mod 3 == 0", p_sum_of_e, n)
bench("sum mod 3 != 0 (max)", p_neg_sum, n)
bench("sum of squares", p_squared_l2, n)
bench("sum descending", p_l1, n)
bench("consecutive equal -", p_count_pairs_match, n)
bench("consecutive different +", p_count_consec_diff, n)

# Two-stage: c2 + a small additive feature
def p_c2_3_with_aff_feat(e, n):
    c2 = sum(1 for x in e if x == 2)
    primary = -abs(c2 - 3) * 1_000_000.0
    # affine subspace feature: linear in e
    aff = (e[0] + e[2] + e[4] + e[6]) % 3
    return primary - float(aff)

bench("c2=3 + even coords sum mod 3", p_c2_3_with_aff_feat, n)

def p_c2_3_alt_aff(e, n):
    c2 = sum(1 for x in e if x == 2)
    primary = -abs(c2 - 3) * 1_000_000.0
    aff = (e[0] + e[1] + e[2] + e[3]) % 3
    return primary - float(aff)

bench("c2=3 + first half sum mod 3", p_c2_3_alt_aff, n)

# Greedy with priority = ELLIPSOID feature
def p_ellipsoid(e, n):
    weights = [1, 2, 3, 4, 5, 6, 7, 8]
    s = sum(w * x * x for w, x in zip(weights, e))
    return -float(s)

bench("ellipsoid -sum w_i x_i^2", p_ellipsoid, n)

def p_funky(e, n):
    s = sum(x * (i+1) * (n-i) for i, x in enumerate(e))
    return -float(s % 3)

bench("funky sum mod 3", p_funky, n)

# Heavy "mass" priorities
print("\n--- combining many features ---")

def p_super(e, n):
    c2 = sum(1 for x in e if x == 2)
    c1 = sum(1 for x in e if x == 1)
    primary = -abs(c2 - 3) * 100000
    sec1 = -abs(c1 - 3) * 100
    sec2 = -float(sum(e) % 3) * 10
    return primary + sec1 + sec2

bench("c2=3 + c1=3 + sum%3==0", p_super, n)

def p_sym(e, n):
    # symmetric in coords
    c0 = sum(1 for x in e if x == 0)
    c1 = sum(1 for x in e if x == 1)
    c2 = sum(1 for x in e if x == 2)
    # priority by partition-balanced composition
    return -float((c0 - 8/3)**2 + (c1 - 8/3)**2 + (c2 - 8/3)**2)

bench("multiset variance from balanced", p_sym, n)

# Specific known construction: take the cap which is the union of cosets
def p_coset_cap(e, n):
    # consider the subgroup generated by (1,1,0,0,0,0,0,0), (0,0,1,1,0,0,0,0), ...
    # paired structure: e[2i] + e[2i+1] = c_i (constant)
    # for cap, want c_i ∈ {0,1,2}
    pair_sums = tuple((e[2*i] + e[2*i+1]) % 3 for i in range(4))
    # all should be in some target
    # pick: prefer sums all 0 (works if other coords are small)
    return -float(sum(s != 0 for s in pair_sums))

bench("paired sum == 0", p_coset_cap, n)
